### ISSUE TITLE
Roadmap to 4.0 version of the library 

### ISSUE THREAD

**Issue by Kacper20** [Polidea/RxBluetoothKit#60]
- [ ] Rewrite tests using RxSwift like approach.
- [ ] Cleanup namings like `monitor`, `rx_[..]` and use one way to describe function that returns observable with infinite stream of values. 
- [ ] Implement `connect` as observable which will perform disconnection when dispose is called on subscribtion. Get rid of `cancelConnection` method.
- [ ] Implement value changed observable, which will automatically set notification flag on characteristic and monitor value changes as long as  subscribtion is valid. Get rid of currently used notification methods.
- [ ] Check if there's a better way to perform equality check of protocol and it's implementation in Swift 3(it hurts us in tests currently).
- [ ] Write in docs that user is not able to monitor descriptors value changed from outside. 
- [ ] Make sure that docs are inline with signatures of the functions.
- [ ] Replace deprecated `OSAtomicCompareAndSwap32` and use function from <stdatomic.h>
- [ ] Support CBPeripheralDelegate: #66 
- [ ] Prepare wiki with most common operations
- [ ] Support Swift Package Manager- #56 
- [ ] Think about giving access to `CBPeripheral` instance - #42 
- [ ] Make needed changes in `BluetoothError` structure, needed by the react-native-ble-plx lib

**Comment by Kacper20** [comment]
This issue has been translated to more instances, in order to better manage them.
